### ISSUE TITLE
The order of `Shell::get_profile_paths` is not consistent among shells; unify and clarify it

### ISSUE THREAD

**Issue by tats-u** [moonrepo/starbase#108]
- https://github.com/moonrepo/starbase/pull/105#issuecomment-2483220788
- https://github.com/moonrepo/proto/issues/655

In Bash, the most preferred *profile* (not rc) comes first:

https://github.com/moonrepo/starbase/blob/9f20f1be896c37081a390f6c06047577692267ae/crates/shell/src/shells/bash.rs#L17-L30

https://github.com/moonrepo/starbase/blob/9f20f1be896c37081a390f6c06047577692267ae/crates/shell/src/shells/bash.rs#L87-L106

In elvish, the most preferred one returned by `get_config_path` comes first while the "legacy" one comes last:

https://github.com/moonrepo/starbase/blob/9f20f1be896c37081a390f6c06047577692267ae/crates/shell/src/shells/elvish.rs#L88-L102

In fish, the return value of `get_config_path` comes first in `get_profile_paths` like the above 2 shells:

https://github.com/moonrepo/starbase/blob/9f20f1be896c37081a390f6c06047577692267ae/crates/shell/src/shells/fish.rs#L64-L79

However, in nushell, the order depends on the hash algorithm of `HashSet`:

https://github.com/moonrepo/starbase/blob/9f20f1be896c37081a390f6c06047577692267ae/crates/shell/src/shells/nu.rs#L132-L150

Proto treats the return value of `get_profile_paths` as least-preferred-comes-first, but its assumption is basically wrong.
Starbase needs to unify and clarify the order of `get_profile_paths`.

**Comment by milesj** [comment]
"Profile" paths can be either actual profile or rc files, it's not just literal profiles. I couldn't think of a better name (naming is hard lol).

I'll fix the ordering though.
