### ISSUE TITLE
Is this a build system? 🤔 

### ISSUE THREAD

**Issue by jmackie** [moonrepo/starbase#21]
Hey!

Super cool project (I think I saw it on the TLDR newsletter, FYI)

My question is very specific and self-serving, but I was just wondering what the intended applications of this are before I go digging around.

Could you build a `make`/`ninja`/etc type CLI with `starbase`?

**Comment by milesj** [comment]
I primarily built starbase for building our proto (https://github.com/moonrepo/proto) and moon (https://github.com/moonrepo/moon) CLIs. Especially moon, since it's very complex, and we needed a better way to structure the app and it's data.

**Comment by justbaileym** [comment]
I found this while looking for an alternative to oclif : 🤔
