### ISSUE TITLE
starbase_archive cannot extract tar.gz created using macos' tar

### ISSUE THREAD

**Issue by Phault** [moonrepo/starbase#56]
I'm trying to create a proto plugin for [ruff](https://github.com/astral-sh/ruff), but hit a snag with the Mac releases. The tar files for Mac are created [using the inbuilt tar of the macos-latest runner](https://github.com/astral-sh/ruff/blob/c007b175bad7ea05c5369ddcf11e6b5f41267398/.github/workflows/release.yaml#L129).

But it turns out that tar version apparently uses a "GNU Sparse File extension", which [tar-rs does not currently support](https://github.com/alexcrichton/tar-rs/issues/295). The result is that extraction spits out a "GNUSparseFile.0" directory containing corrupted archive files.

[There is an old PR lying around to fix this, but it has been stale for 2 years.](https://github.com/alexcrichton/tar-rs/pull/298). The [cargo-binstall](https://github.com/cargo-bins/cargo-binstall) guys created a [temporary fork with the fix](https://github.com/cargo-bins/tar-rs), while they wait for the PR to get merged. So that's one way to go at least.

You can test it yourself on a Mac using https://github.com/Phault/proto-toml-plugins/tree/main/ruff

**Comment by milesj** [comment]
Unfortunate but switching https://github.com/moonrepo/starbase/pull/60
