### ISSUE TITLE
[Bounty] Support shell value quoting

### ISSUE THREAD

**Issue by milesj** [moonrepo/starbase#81]
Our [starbase_shell](https://github.com/moonrepo/starbase/tree/master/crates/shell) crate supports many CLI shells for formatting environment variables and appending `PATH` using shell specific syntax. The current implementation "works" but it assumes the formatted values are trivial, and do not include non-trivial values (spaces, required escaping, etc).

We should add a `Shell.quote` method to each shell, that follows the escaping/quoting rules of that shell, since all shells have their own custom syntax and rules.

```rust
pub trait Shell {
    // ...
    fn quote(&self, value: &str) -> String;
}
```

Furthermore, existing methods should be updated to use the quoting. For example:

```rust
// Before
fn format_env_set(&self, key: &str, value: &str) -> String {
    format!(r#"export {key}="{value}";"#)
}

// After
fn format_env_set(&self, key: &str, value: &str) -> String {
    format!("export {}={};", self.quote(key), self.quote(value))
}
```

## Requirements

- Ideally the quoting is incremental. For example, in Bash, if passed a simple value, it's not quoted.

```
export KEY=value
```

But if it contains values that need quoting, then wrap with quotes.

```
export KEY="value with spaces"
```

And if it really needs special quoting syntax for complex values, then finally use that.

```
export KEY=$'value with spaces and escapes, etc'
```

- Try to avoid pulling in additional dependencies. At maximum, only 1 dependency is allowed.

**Comment by milesj** [comment]
All shells must be implemented to qualify for the bounty!

**Comment by deepakdinesh1123** [comment]
/attempt #81

@milesj can I work on this?

**Comment by milesj** [comment]
Go for got! Just be sure to rebase after this PR lands: https://github.com/moonrepo/starbase/pull/80

**Comment by deepakdinesh1123** [comment]
@milesj Since the number of formats in which environment variable values can be specified are not too many for a particular shell , I was thinking of using regex to match the pattern in which the value and keys are defined and change the command accordingly, please let me know if this implementation plan seems okay to you and if I need to make any changes

**Comment by milesj** [comment]
@deepakdinesh1123 You have a quick example of how this would work? Could just be some pseudo code example.

**Comment by urbit-pilled** [comment]
cancelling my attempt because @varshith257's PR seems to have made enough progress with this issue.

**Comment by varshith257** [comment]
@abhishek818 I wanted to touch base regarding the work we're both tackling. I've been heavily invested in resolving the issues and making progress.  I'm currently actively engaged in resolving the issues and making progress. I kindly request that you hold off on proceeding with this particular task until I've had a chance to complete my attempt. If for any reason I decide not to continue, I'll let you know, and you're welcome to take it forward.

Hope you consider it @abhishek818

**Comment by milesj** [comment]
Thanks everyone for your interest in this bounty. This is my first time using Algolia, so I'm still learning the workflows, so sorry for all the confusion!

With that said, I'll be going with @varshith257's PR, simply because it seems further along, and hits all the requirements. @abhishek818 I'll send you a tip for the work you've done so far, since you spent a good amount of time on it already.

In the near future, I'll have a lot more bounties for starbase, proto, and moon. I just need to find the time to write up all the issues.
