### ISSUE TITLE
Don't newly create `.bash_profile`

### ISSUE THREAD

**Issue by tats-u** [moonrepo/starbase#99]
https://github.com/moonrepo/starbase/blob/aa293bafa9094866e0ec030fa82e643c4472b2aa/crates/shell/src/shells/bash.rs#L72-L86

In the initial environment in Ubuntu, there is no `.bash_profile`.

```
$ docker run -it --rm ubuntu ls -A /home/ubuntu
.bash_logout  .bashrc  .profile
```

If there is `.bash_profile`, `.profile` will not be read. Ubuntu has set up some initial configurations in `.profile`.

```
$ docker run -it --rm ubuntu cat /home/ubuntu/.profile
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
```

Other tools that don't use this library add their configurations to `.profile` (if there's no `.bash_profile`).
If a tool like Proto tries to create `.bash_profile` despite the existence of `.profile`, such configurations will never be loaded anymore.
This bad "specification" discourages us from adopting Proto in Ubuntu or other Debian-based Linux distros.

**Comment by milesj** [comment]
This seems fair. I'm a bit swamped right now, can you maybe give it a shot? Cool if not.

**Comment by milesj** [comment]
No worries, I'll try to get around to it soon.
